from langchain_core.tools import tool
import subprocess
import os
import uuid

@tool
def run_code(code: str) -> dict:
    """
    Execute autogenerated Python code in a sandbox-like directory.

    The code is stored temporarily in /LLMFiles and executed
    using a fresh Python process.
    """
    try:
        # Create directory if missing
        os.makedirs("LLMFiles", exist_ok=True)

        # Unique filename to avoid collisions
        file_id = uuid.uuid4().hex[:8]
        filename = f"run_{file_id}.py"
        filepath = os.path.join("LLMFiles", filename)

        # Write code to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(code)

        # Run with system python, not 'uv'
        proc = subprocess.Popen(
            ["python", filename],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd="LLMFiles"  # ensure imports & files local to script
        )
        stdout, stderr = proc.communicate()

        return {
            "stdout": stdout,
            "stderr": stderr,
            "return_code": proc.returncode
        }

    except Exception as e:
        return {
            "stdout": "",
            "stderr": f"Execution failed: {str(e)}",
            "return_code": -1
        }
